spring:
  application:
    name: @pom.artifactId@
  security:
    user:
      password: asd123
server:
  servlet:
    context-path: /resource
  port: 8035

security:
  oauth2:
    client:
      client-id: client-test-d
      client-secret: 123456
      # 获取访问令牌接口
      access-token-uri: http://localhost:8030/example-auth/oauth/token
      resource-ids: resourceApp-b
      scope: write
      # app 端服务授权模式
      grant-type: password
    resource:
      jwt:
        # 获取 tokenKey,（校验token签名）
        key-uri: http://localhost:8030/example-auth/oauth/token_key