spring:
  application:
    name: @pom.artifactId@
  security:
    user:
      name: webclient
      password: asd123

server:
  servlet:
    context-path: /client-web
  port: 8031


security:
  oauth2:
    client:
      client-id: auth-client-a
      client-secret: 123456
      user-authorization-uri: http://localhost:8030/example-auth/oauth/authorize
      access-token-uri: http://localhost:8030/example-auth/oauth/token
      resource-ids: resourceApp-b
      registered-redirect-uri: http://localhost:${server.port}/${server.servlet.context-path}/login
      scope: write
    resource:
      jwt:
        key-uri: http://localhost:8030/example-auth/oauth/token_key
