spring:
  application:
    name: @pom.artifactId@
  mvc:
    servlet:
      load-on-startup: 0
#  security:
#    user:
#      name: webclient
#      password: asd123

server:
  servlet:
    context-path: /client-admin
  port: 8032

security:
  oauth2:
    client:
      client-id: k-service-client
      client-secret: 123456
      user-authorization-uri: http://localhost:8030/example-auth/oauth/authorize
      access-token-uri: http://localhost:8030/example-auth/oauth/token
      resource-ids: resourceApp-b
      registered-redirect-uri: http://localhost:${server.port}/${server.servlet.context-path}/login
      scope: read
    resource:
      jwt:
        key-uri: http://localhost:8030/example-auth/oauth/token_key
