spring:
  application:
    name: @pom.artifactId@
  redis:
    host: 127.0.0.1
    password: password
    port: 6382
    timeout: 3000
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
        min-idle: 0
server:
  port: 8030
  servlet:
    context-path: /example-auth