spring:
  application:
    name: @pom.artifactId@
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2-server?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: qweqwe
  redis:
    host: 127.0.0.1
    password: password
    port: 6382
    timeout: 3000
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1ms
        min-idle: 0
server:
  port: 8030
  servlet:
    context-path: /example-auth

# Logging
logging:
  level:
    root: info
    club.example.oauth2.server.repository: trace

# mybatis
mybatis-plus:
  type-aliases-package: club.example.oauth2.server.entity
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: none
  #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    cache-enabled: false
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler

oauth2:
  security:
    jwt:
      sign-key: jwtSignKey
    authorization-code:
      expiration : 300

# 资源自有服务器
#security:
#  oauth2:
#    client:
#      client-id: authorization-admin-gr8xjo2c
#      client-secret: password.admin
#      access-token-uri: http://localhost:${server.port}/${server.servlet.context-path}/oauth/token
#      resource-ids: resourceApp-b
#      scope: read,write
#      grant-type: password
#    resource:
#      jwt:
#        key-uri: http://localhost:${server.port}/${server.servlet.context-path}/oauth/token_key