spring:
  application:
    name: @pom.artifactId@

server:
  port: 8036
  servlet:
    context-path: /resource-service

security:
  oauth2:
    client:
      client-id: client-test-e
      client-secret: 123456
      # 获取访问令牌接口
      access-token-uri: http://localhost:8030/example-auth/oauth/token
      resource-ids: resourceApp-b
      scope: write
      # app 端服务授权模式
      grant-type: password
    resource:
      jwt:
        # 获取 tokenKey,（校验token签名）
        key-uri: http://localhost:8030/example-auth/oauth/token_key